#https://docs.astral.sh/ruff/configuration/
[tool.ruff]
line-length = 180

[tool.ruff.format]
indent-style = "space"

#https://microsoft.github.io/pyright/#/configuration?id=sample-pyprojecttoml-file
[tool.pyright]
exclude = ["**/__pycache__"]
extraPaths = []
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportOptionalMemberAccess = false
reportFunctionMemberAccess = false
reportAttributeAccessIssue = false
reportGeneralTypeIssues = false
